Repository zimmerman-team/IATI.cloud, pull requests merged in 2019-09, with the labels that each got.

#1719 OIPA-1715
  OIPA/api/activity/filters.py
Labels: size/XS

#1728 bug/OIPA-1724
  OIPA/api/activity/views.py
Labels: size/XS

#1730 feature/OIPA-1729
  OIPA/api/activity/filters.py
Labels: size/XS

#1706 MLT-359
  OIPA/solr/result/conf/data-config.xml
  OIPA/solr/result/conf/managed-schema
Labels: size/XS

#1712 MLT-360
  OIPA/solr/transaction/conf/data-config.xml
  OIPA/solr/transaction/conf/managed-schema
Labels: size/M

#1731 bug/OIPA-1683
  OIPA/iati/parser/parse_manager.py
Labels: size/XS

#1734 DS-198
  .circleci/config.yml
Labels: size/M

#1717 enhancement/OIPA-1688
  OIPA/OIPA/settings.py
Labels: size/XS

#1716 enhancement/OIPA-1696
  OIPA/api/views.py
Labels: size/L

#1735 bug/OIPA-1703
  OIPA/api/iati/references.py
  OIPA/iati/migrations/0064_auto_20190904_1412.py
  OIPA/iati/migrations/0065_auto_20190904_1423.py
  OIPA/iati/models.py
Labels: size/M

#1738 bug/OIPA-1737
  OIPA/api/iati/references.py
Labels: size/S

#1739 MLT-410
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/result/conf/managed-schema
Labels: size/S

#1743 bug/OIPA-1741
  OIPA/iati/parser/parse_manager.py
Labels: size/XS

#1742 MLT-355
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
Labels: size/M

#1745 bug/OIPA-1740
  OIPA/api/iati/references.py
Labels: size/XS

#1748 MLT-409
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
Labels: size/L

#1750 MLT-414
  OIPA/solr/activity/conf/data-config.xml
Labels: size/L

#1749 bug/OIPA-1744
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
Labels: size/L

#1753 DS-226
  OIPA/solr/activity/conf/managed-schema
Labels: size/M

#1754 DS-200
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/default_aid_type.sql
Labels: size/S

#1755 DS-228
  OIPA/iati/parser/IATI_2_02.py
Labels: size/XS

#1752 feature/OIPA-1751
  OIPA/api/iati/references.py
  OIPA/api/renderers.py
Labels: size/S

#1761 enhancement/OIPA-1723
  OIPA/api/activity/serializers.py
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/urls.py
  OIPA/api/organisation/views.py
Labels: size/L

#1768 enhancement/OIPA-1762
  OIPA/api/organisation/urls.py
  OIPA/api/organisation/views.py
Labels: size/S

#1769 enhancement/OIPA-1756
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/urls.py
  OIPA/api/organisation/views.py
Labels: size/S

#1771 DS-230
  OIPA/solr/activity/conf/managed-schema
Labels: size/M

#1770 enhancement/OIPA-1758
  OIPA/api/organisation/urls.py
  OIPA/api/organisation/views.py
Labels: size/S

#1778 MLT-413
  OIPA/solr/result/conf/data-config.xml
  OIPA/solr/result/conf/sql/resultreference.sql
Labels: size/M

#1781 enhancement/OIPA-1776
  OIPA/api/activity/serializers.py
  OIPA/api/activity/views.py
  OIPA/api/iati/references.py
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/tests/test_save_serializers.py
  OIPA/api/organisation/views.py
Labels: size/L

#1779 MLT-453
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/document_link.sql
Labels: size/L

#1782 MLT-415
  OIPA/solr/transaction/conf/data-config.xml
  OIPA/solr/transaction/conf/managed-schema
Labels: size/M

#1783 bug/OIPA-1747
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_prefetches.py
  OIPA/api/activity/tests/test_save_serializers.py
  OIPA/iati/factory/iati_factory.py
  OIPA/iati/migrations/0066_auto_20190916_1456.py
  OIPA/iati/models.py
  OIPA/iati_codelists/factory/codelist_factory.py
Labels: size/S

#1785 chore: typo change
  OIPA/iati/parser/IATI_2_02.py
Labels: size/XS

#1784 MLT-442
  OIPA/solr/organisation/conf/data-config.xml
  OIPA/solr/organisation/conf/managed-schema
  OIPA/solr/organisation/conf/sql/document_link.sql
  OIPA/solr/organisation/conf/sql/name.sql
  OIPA/solr/organisation/conf/sql/name_narrative.sql
  OIPA/solr/organisation/conf/sql/recipient_country_budget.sql
  OIPA/solr/organisation/conf/sql/recipient_org_budget.sql
  OIPA/solr/organisation/conf/sql/recipient_region_budget.sql
  OIPA/solr/organisation/conf/sql/total_budget.sql
  OIPA/solr/organisation/conf/sql/total_expenditure.sql
Labels: size/XL

#1786 MLT-442-01
  OIPA/solr/organisation/conf/data-config.xml
Labels: size/XS

#1787 MLT-463
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/sql/location.sql
Labels: size/L

#1788 MLT-464
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/sql/contact_info.sql
Labels: size/L

#1789 DS-259
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/activity_date.sql
Labels: size/M

#1790 IATI-DATASTORE-1697
  OIPA/iati_organisation/parser/organisation_2_03.py
Labels: size/XS

#1791 MLT-469
  OIPA/solr/activity/conf/data-config.xml
Labels: size/S

#1792 MLT-473
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/conditions.sql
  OIPA/solr/activity/conf/sql/legacy_data.sql
  OIPA/solr/activity/conf/sql/location.sql
  OIPA/solr/activity/conf/sql/related_activity.sql
Labels: size/L

#1795 MLT-475
  OIPA/solr/activity/conf/data-config.xml
Labels: size/XS

#1796 DS-286
  OIPA/solr/participating_org/conf/data-config.xml
  OIPA/solr/participating_org/conf/managed-schema
Labels: size/XXL

#1800 OIPA-1799
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/transaction/conf/data-config.xml
Labels: INDEXING, SOLR, size/XL

#1801 DS-290
  OIPA/solr/transaction/conf/data-config.xml
Labels: INDEXING, SOLR, size/XS

#1802 DS-291
  OIPA/solr/transaction/conf/data-config.xml
Labels: size/XS

#1804 bug/OIPA-1793
  OIPA/iati/migrations/0067_auto_20190926_1550.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
Labels: size/S

#1807 OIPA-1806
  OIPA/iati/activity_search_indexes.py
Labels: size/XS

#1808 OIPA-1805
  OIPA/solr/result/conf/data-config.xml
Labels: size/XL

#1811 OIPA-1803
  OIPA/iati_organisation/migrations/0006_organisation_last_updated_model.py
  OIPA/iati_organisation/models.py
  OIPA/solr/organisation/conf/data-config.xml
Labels: FEATURE, INDEXING, SOLR, size/M

#1812 MLT-417
  OIPA/solr/activity/conf/data-config.xml
Labels: FEATURE, INDEXING, SOLR, size/XS
