Repository zimmerman-team/IATI.cloud, pull requests merged in 2019-08, with the labels that each got.

#1588 OIPA-1585
  OIPA/api/activity/filters.py
Labels: size/L

#1589 OIPA-1587
  OIPA/api/budget/views.py
Labels: size/XS

#1555 OIPA-1502
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/iati_synchroniser/tests/test_codelist_importer.py
  OIPA/task_queue/tasks.py
  OIPA/templates/django_rq/stats.html
Labels: CODELISTS, FEATURE

#1590 OIAP0-1584
  OIPA/api/activity/filters.py
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_prefetches.py
  OIPA/api/activity/tests/test_save_serializers.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/budget/filters.py
  OIPA/api/permissions/tests/test_activity_permissions.py
  OIPA/api/region/serializers.py
  OIPA/api/region/tests/test_serializers.py
  OIPA/api/result/filters.py
  OIPA/api/transaction/filters.py
  OIPA/api/transaction/views.py
  OIPA/iati/factory/iati_factory.py
  OIPA/iati/management/commands/data_migrations_from_default_aid_type_to_default_aid_types.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/tests/test_parser_fields.py
  OIPA/iati_synchroniser/tests/test_codelist_importer.py
Labels: size/L

#1603 bug/OIPA-1599
  OIPA/iati/parser/IATI_2_03.py
Labels: size/XS

#1602 OIPA-1601
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/activity_date.sql
  OIPA/solr/activity/conf/sql/budget.sql
  OIPA/solr/activity/conf/sql/contact_info.sql
  OIPA/solr/activity/conf/sql/country_budget_items.sql
  OIPA/solr/activity/conf/sql/default_aid_type.sql
  OIPA/solr/activity/conf/sql/description.sql
  OIPA/solr/activity/conf/sql/humanitarian_scope.sql
  OIPA/solr/activity/conf/sql/location.sql
  OIPA/solr/activity/conf/sql/other_identifier.sql
  OIPA/solr/activity/conf/sql/participating_org.sql
  OIPA/solr/activity/conf/sql/planned_disbursement.sql
  OIPA/solr/activity/conf/sql/policy_marker.sql
  OIPA/solr/activity/conf/sql/recipient_country.sql
  OIPA/solr/activity/conf/sql/recipient_region.sql
  OIPA/solr/activity/conf/sql/reporting_org.sql
  OIPA/solr/activity/conf/sql/sector.sql
  OIPA/solr/activity/conf/sql/tag.sql
  OIPA/solr/activity/conf/sql/title.sql
  OIPA/solr/activity/conf/sql/transaction.sql
  OIPA/solr/budget/conf/data-config.xml
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/default/conf/solrconfig.xml
  OIPA/solr/organisation/conf/data-config.xml
  OIPA/solr/organisation/conf/managed-schema
  OIPA/solr/publisher/conf/data-config.xml
  OIPA/solr/publisher/conf/managed-schema
  OIPA/solr/readme.md
  OIPA/solr/result/conf/data-config.xml
  OIPA/solr/result/conf/managed-schema
  OIPA/solr/transaction/conf/data-config.xml
  OIPA/solr/transaction/conf/managed-schema
Labels: size/XXL

#1600 test/OIPA-1594
  OIPA/api/activity/tests/test_activities_csv_endpoints.py
Labels: size/L

#1606 OIPA-1605
  OIPA/api/renderers.py
Labels: size/S

#1608 feature/OIPA-1604
  OIPA/api/activity/views.py
  OIPA/api/renderers.py
Labels: size/M

#1614 OIAP-1611
  OIPA/OIPA/settings.py
  OIPA/OIPA/urls.py
  OIPA/OIPA/views.py
  OIPA/api/organisation/tests/test_organisation_csv_endpoint.py
  OIPA/api/tests/test_export.py
Labels: size/XS

#1625 bug/OIPA-1624
  OIPA/iati_organisation/parser/organisation_2_01.py
Labels: size/XS

#1626 bug/OIPA-1620
  OIPA/api/iati/references.py
Labels: size/XS

#1631 bug/OIPA-1630
  OIPA/iati/parser/iati_parser.py
Labels: size/XS

#1637 MLT-317
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/activity.sql
Labels: size/XL

#1615 OIPA-1612
  OIPA/api/renderers.py
Labels: size/XS

#1651 OIPA-1627-03
  OIPA/api/iati/elements.py
  OIPA/api/iati/references.py
  OIPA/api/renderers.py
Labels: size/L

#1654 OIPA-1646
  OIPA/api/iati/references.py
Labels: size/XS

#1655 bug/OIPA-1653
  OIPA/api/activity/filters.py
Labels: size/XS

#1642 MLT-322
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/reporting_org.sql
Labels: size/M

#1658 OIPA-1628
  OIPA/api/activity/serializers.py
  OIPA/api/iati/references.py
Labels: size/M

#1659 MLT-336
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/sql/activity.sql
Labels: size/S

#1670 enhancement/OIPA-1666
  OIPA/api/renderers.py
Labels: size/XS

#1684 enhancement/OIPA-1682
  OIPA/api/pagination.py
Labels: size/XS

#1689 enhancement/OIPA-1657
  OIPA/api/organisation/serializers.py
  OIPA/iati_organisation/migrations/0005_organisation_dataset.py
  OIPA/iati_organisation/models.py
  OIPA/iati_organisation/parser/organisation_2_01.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_organisation/parser/organisation_2_03.py
Labels: size/M

#1692 feature/OIPA-1690
  OIPA/api/renderers.py
Labels: size/M

#1698 enhancement/OIPA-1685
  OIPA/api/dataset/serializers.py
Labels: size/XS

#1701 enhancement/OIPA-1687
  OIPA/api/iati/references.py
Labels: size/XS

#1705 MLT-358
  OIPA/solr/transaction/conf/managed-schema
Labels: size/XS

#1704 MLT-339-01
  OIPA/solr/activity/conf/data-config.xml
  OIPA/solr/activity/conf/managed-schema
Labels: size/L

#1710 feature/OIPA-1690
  OIPA/api/renderers.py
Labels: size/S

#1709 bug/OIPA-1707
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/tests/test_parser_fields.py
Labels: size/M
