Repository zimmerman-team/IATI.cloud, pull requests merged in 2019-11, with the labels that each got.

#1905 Patch/schema error
  OIPA/solr/activity/conf/managed-schema
Labels: size/M

#1906 Develop
  OIPA/solr/activity/conf/managed-schema
Labels: size/M

#1908 MLT-696
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_organisation/parser/organisation_2_01.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_organisation/parser/organisation_2_03.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/default/realtime/conf/solrconfig.xml
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/solr/utils.py
Labels: size/XXL

#1909 Develop
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_organisation/parser/organisation_2_01.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_organisation/parser/organisation_2_03.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/default/realtime/conf/solrconfig.xml
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/solr/utils.py
Labels: size/XXL

#1911 MLT-697
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/organisation/indexing.py
  OIPA/solr/transaction/indexing.py
Labels: size/M

#1913 Should be date string solr
  OIPA/solr/organisation/indexing.py
Labels: size/XS

#1923 OIPA-1921
  OIPA/api/activity/serializers.py
  OIPA/iati/parser/validators.py
Labels: size/L

#1917 OIPA-1910
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_prefetches.py
  OIPA/api/activity/tests/test_save_serializers.py
  OIPA/api/iati/references.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_03.py
Labels: size/S

#1924 OIPA-1843
  OIPA/templates/404.html
  OIPA/templates/500.html
Labels: size/S

#1925 DS-382
  OIPA/OIPA/settings.py
  OIPA/supervisord.conf
  OIPA/task_queue/tasks.py
  OIPA/templates/django_rq/stats.html
Labels: size/M

#1930 iati.cloud#1926
  OIPA/solr/activity/indexing.py
Labels: size/M

#1939 OIPA-1938
  OIPA/iati_organisation/parser/organisation_2_03.py
Labels: size/XS

#1932 iati.cloud-1918
  OIPA/solr/activity/indexing.py
Labels: size/XS

#1933 iati.cloud-1920
  OIPA/solr/result/indexing.py
Labels: size/XS

#1936 iati.cloud-1919
  OIPA/solr/activity/indexing.py
Labels: size/XS

#1940 iati.cloud-1851
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/result/conf/managed-schema
  OIPA/solr/transaction/conf/managed-schema
Labels: size/M

#1949 iati.cloud-1941
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/models.py
  OIPA/solr/dataset/conf/managed-schema
  OIPA/supervisord.conf
Labels: size/L

#1955 OIPA-1935
  OIPA/iati/PostmanJsonImport/importPostmanJson.py
Labels: size/M

#1954 iati.cloud-1662
  OIPA/api/activity/filters.py
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_activity_endpoints.py
  OIPA/api/activity/tests/test_serializers.py
Labels: size/S

#1958 iati.cloud-1944
  OIPA/iati/PostmanJsonImport/importPostmanJson.py
  OIPA/solr/cron/backup-zip.sh
  OIPA/solr/cron/backup.sh
  OIPA/solr/cron/database-dump.sh
  OIPA/solr/cron/download-snapshop.sh
Labels: size/XS

#1961 iati.cloud-1956
  OIPA/solr/activity/indexing.py
Labels: size/XS

#1964 iati.cloud-1963
  OIPA/solr/activity/indexing.py
Labels: size/M

#1967 iati.cloud-1965
  OIPA/solr/activity/indexing.py
Labels: size/M

#1968 iati.cloud-1966
  OIPA/solr/activity/indexing.py
Labels: size/M

#1950 OIPA-1678
  OIPA/iati/activity_aggregation_calculation.py
Labels: size/S

#2008 iati.cloud-1998
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/references.py
  OIPA/solr/transaction/references.py
Labels: INDEXING, SOLR, size/L

#2010 iati.cloud-2009
  OIPA/api/renderers.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_synchroniser/models.py
  OIPA/solr/activity/indexing.py
  OIPA/solr/signals.py
  OIPA/solr/utils.py
  OIPA/supervisord.conf
  OIPA/task_queue/tasks.py
  OIPA/templates/django_rq/stats.html
Labels: size/L

#2011 iati.cloud-1994
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/budget/references.py
Labels: size/S

#2012 iati.cloud-2004
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/result/references.py
Labels: size/S

#2013 iati.cloud-1972
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/M

#2014 iati.cloud-1973
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/M

#2015 iati.cloud-1974
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/S

#2016 iati.cloud-1975
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/M

#2017 iati.cloud-1976
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/M

#2019 iati.cloud-2018
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/S

#2020 iati.cloud-1977
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/M

#2021 iati.cloud-1978
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/M

#2022 iati.cloud-1979
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/S

#2023 iati.cloud-1981
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/references.py
Labels: size/S
