Repository zimmerman-team/IATI.cloud, pull requests merged in 2019-05, with the labels that each got.

#1222 OIPA-1221
  OIPA/iati_synchroniser/codelist_importer.py
Labels: BUG, SECURITY

#1212 OIPA-1209
  OIPA/api/activity/serializers.py
  OIPA/api/iati/references.py
Labels: 2.03, DS PHASE 1, FEATURE

#1235 OIPA-1224
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/static/xml/activity-standard-example-annotated.xml
Labels: 2.03, PARSER

#1250 OIPA-1244
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_prefetches.py
Labels: API, BUG, FEATURE

#1245 OIPA-1240
  OIPA/api/activity/serializers.py
  OIPA/api/budget/urls.py
  OIPA/api/budget/views.py
  OIPA/static/datasets
Labels: API, FEATURE

#1214 OIPA-1210
  OIPA/api/iati/elements.py
Labels: 2.03, DS PHASE 1, FEATURE

#1215 OIPA-1208
  OIPA/iati/parser/IATI_2_03.py
Labels: 2.03, API, BUG, DS PHASE 1

#1216 OIPA-1197
  OIPA/api/iati/references.py
Labels: 2.03, DS PHASE 1, FEATURE

#1219 OIPA-1182
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_prefetches.py
  OIPA/api/iati/references.py
  OIPA/static/xml/activity-standard-example-annotated.xml
Labels: 2.03, BUG, DS PHASE 1, FEATURE

#1236 OIPA-1217
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_codelists/migrations/0012_budget_identifier_category_null_true.py
  OIPA/iati_codelists/models.py
  OIPA/static/xml/activity-standard-example-annotated.xml
Labels: 2.03, PARSER

#1238 OIPA-1233
  OIPA/api/iati/references.py
Labels: BUG, CODELISTS, DS PHASE 1, FEATURE

#1242 OIPA-1239
  OIPA/.gitignore
  OIPA/api/dataset/serializers.py
  OIPA/api/dataset/views.py
  OIPA/iati_synchroniser/models.py
Labels: BUG, FEATURE

#1248 OIPA-1229
  OIPA/api/iati/references.py
Labels: DS PHASE 1, FEATURE

#1251 OIPA-1231
  OIPA/api/activity/serializers.py
Labels: API, BUG, DS PHASE 1

#1253 OIPA-1237
  OIPA/iati/parser/IATI_2_03.py
Labels: BUG, PARSER

#1254 OIPA-1234
  OIPA/api/activity/serializers.py
Labels: API, BUG

#1255 OIPA-1230
  OIPA/iati_synchroniser/codelist_importer.py
Labels: 2.03, BUG, PARSER

#1257 OIPA-1228
  OIPA/static/xml/activity-standard-example-annotated.xml
Labels: 2.03, BUG

#1258 OIPA-1226
  OIPA/api/activity/serializers.py
Labels: 2.03, BUG, DS PHASE 1

#1259 OIPA-1227
  OIPA/iati/parser/IATI_2_03.py
Labels: 2.03, BUG, PARSER

#1260 OIPA-1247
  OIPA/iati/parser/IATI_2_03.py
Labels: 2.03, BUG, PARSER

#1261 OIPA-1252
  OIPA/api/dataset/views.py
Labels: API, DS PHASE 1, FEATURE

#1263 OIPA-1262
  OIPA/iati/parser/parse_manager.py
Labels: DS PHASE 1, FEATURE, PARSER

#1268 OIPA-1267
  OIPA/api/activity/serializers.py
  OIPA/api/codelist/serializers.py
Labels: API, DS PHASE 1, FEATURE

#1269 OIPA-1266
  OIPA/api/iati/references.py
Labels: DS PHASE 1, FEATURE

#1270 OIPA-1264
  OIPA/api/iati/references.py
Labels: DS PHASE 1, FEATURE

#1274 OIPA-1265
  OIPA/iati_codelists/migrations/0013_category_null_on_aid_type.py
  OIPA/iati_codelists/models.py
  OIPA/iati_synchroniser/codelist_importer.py
Labels: 2.03, DS PHASE 1, IATI VERSIONING, PARSER

#1276 OIPA-1271
  OIPA/api/organisation/serializers.py
  OIPA/static/xml/organisation-standard-example-annotated.xml
Labels: 2.03, API, FEATURE, IATI VERSIONING

#1302 OIPA-1298
  OIPA/api/iati/elements.py
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/views.py
  OIPA/api/renderers.py
Labels: DS PHASE 1, FEATURE

#1306 OIPA-1305
  OIPA/api/iati/references.py
  OIPA/api/renderers.py
Labels: 2.03, FEATURE, XML EXPORT

#1331 SD-285
  OIPA/iati_synchroniser/codelist_importer.py
Labels: BUG

#1408 SD-297
  OIPA/iati_synchroniser/data/iom_sectors.json
Labels: FEATURE
