Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-11, with the labels that each got.

#2312 Relicensed to Zimmerman
  LICENSE.MD
Labels: size/XS

#2493 usd conversion
  OIPA/OIPA/urls.py
  OIPA/currency_convert/convert.py
  OIPA/currency_convert/imf_rate_parser.py
  OIPA/currency_convert/migrations/0002_monthlyaverage_imf_url.py
  OIPA/currency_convert/models.py
  OIPA/iati/migrations/0072_auto_20201020_0842.py
  OIPA/iati/migrations/0073_auto_20201020_1014.py
  OIPA/iati/migrations/0074_auto_20201020_1048.py
  OIPA/iati/migrations/0075_auto_20201020_1205.py
  OIPA/iati/migrations/0076_auto_20201106_1302.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati/transaction/models.py
  OIPA/iati_organisation/migrations/0007_auto_20201021_0834.py
  OIPA/iati_organisation/migrations/0008_auto_20201021_0844.py
  OIPA/iati_organisation/models.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0020_auto_20201102_2000.py
  OIPA/iati_synchroniser/models.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity-xml.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
  OIPA/solr/dataset/conf/managed-schema
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/solr/utils.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
  OIPA/task_queue/download.py
  OIPA/templates/two_factor/_base.html
  OIPA/templates/two_factor/_base_focus.html
Labels: size/XL

#2487 OIPA-2467
  OIPA/api/dataset/serializers.py
  OIPA/api/dataset/urls.py
  OIPA/api/dataset/views.py
Labels: size/M

#2500 OIPA-2498
  OIPA/api/activity/urls.py
Labels: BUG, size/XS

#2505 release
  LICENSE.MD
  OIPA/OIPA/settings.py
  OIPA/api/activity/urls.py
  OIPA/api/budget/filters.py
  OIPA/api/country/filters.py
  OIPA/api/dataset/serializers.py
  OIPA/api/dataset/urls.py
  OIPA/api/dataset/views.py
  OIPA/api/publisher/filters.py
  OIPA/api/transaction/views.py
  OIPA/currency_convert/convert.py
  OIPA/currency_convert/imf_rate_parser.py
  OIPA/currency_convert/migrations/0002_monthlyaverage_imf_url.py
  OIPA/currency_convert/models.py
  OIPA/iati/migrations/0072_auto_20201020_0842.py
  OIPA/iati/migrations/0073_auto_20201020_1014.py
  OIPA/iati/migrations/0074_auto_20201020_1048.py
  OIPA/iati/migrations/0075_auto_20201020_1205.py
  OIPA/iati/migrations/0076_auto_20201106_1302.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/transaction/models.py
  OIPA/iati_organisation/migrations/0007_auto_20201021_0834.py
  OIPA/iati_organisation/migrations/0008_auto_20201021_0844.py
  OIPA/iati_organisation/models.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/requirements.txt
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity-xml.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/tasks.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
  OIPA/solr/dataset/conf/managed-schema
  OIPA/solr/publisher/conf/managed-schema
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/solr/utils.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
Labels: size/XL

#2510 add ReadTimeout Error pass
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/task_queue/download.py
Labels: size/XS
