Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-01, with the labels that each got.

#2060 OIPA-1675
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_activities_csv_endpoints.py
  OIPA/api/activity/tests/test_activity_endpoints.py
  OIPA/api/activity/tests/test_save_serializers.py
  OIPA/api/budget/serializers.py
  OIPA/api/dataset/serializers.py
  OIPA/api/dataset/tests/test_dataset_serializers.py
  OIPA/api/documents/serializers.py
  OIPA/api/generics/views.py
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/tests/test_save_serializers.py
  OIPA/api/publisher/serializers.py
  OIPA/api/tests/test_export.py
  OIPA/api/transaction/serializers.py
Labels: size/S

#2071 iati.cloud-2037
  OIPA/.gitignore
  OIPA/OIPA/development_settings.py
  OIPA/OIPA/settings.py
  OIPA/OIPA/urls.py
  OIPA/requirements.txt
  OIPA/solr/signals.py
  OIPA/task_queue/tasks.py
  OIPA/task_queue/utils.py
  OIPA/templates/404.html
  OIPA/templates/500.html
  OIPA/templates/admin/base.html
  OIPA/templates/admin/base_site.html
  OIPA/templates/admin/geodata/change_list.html
  OIPA/templates/admin/iati/activity/change_form.html
  OIPA/templates/admin/iati/result/change_form.html
  OIPA/templates/admin/iati/transaction/change_form.html
  OIPA/templates/admin/iati_synchroniser/codelist/change_list.html
  OIPA/templates/admin/iati_synchroniser/codelistsync/change_list.html
  OIPA/templates/admin/iati_synchroniser/dataset/change_list.html
  OIPA/templates/admin/related_widget_wrapper.html
  OIPA/templates/admin/submit_line.html
  OIPA/templates/admin/task_queue/add_task.html
  OIPA/templates/admin/task_queue/scheduler.html
  OIPA/templates/django_rq/delete_job.html
  OIPA/templates/django_rq/index.html
  OIPA/templates/django_rq/job_detail.html
  OIPA/templates/django_rq/jobs.html
  OIPA/templates/django_rq/stats.html
  OIPA/templates/home/about.html
  OIPA/templates/home/home.html
  OIPA/templates/nesting/admin/inlines/stacked.html
  OIPA/templates/rest_framework/api.html
Labels: size/XXL

#2079 Added XSLT CSV export to Solr
  OIPA/api/generics/views.py
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/solr/activity/conf/xslt/activity-xml.xsl
Labels: size/XL
