Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-08, with the labels that each got.

#2380 sha1-update
  OIPA/api/dataset/serializers.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0018_dataset_sync_sha1.py
  OIPA/iati_synchroniser/models.py
Labels: size/M

#2384 sha1 update
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/codelist/serializers.py
  OIPA/api/dataset/serializers.py
  OIPA/api/iati/references.py
  OIPA/api/transaction/serializers.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0018_dataset_sync_sha1.py
  OIPA/iati_synchroniser/migrations/0019_merge_20200804_1549.py
  OIPA/iati_synchroniser/models.py
  OIPA/solr/activity/references.py
  OIPA/solr/activity/serializers.py
  OIPA/task_queue/download.py
Labels: size/L

#2391 update_transaction_in_activity_indexing
  OIPA/iati/parser/parse_manager.py
  OIPA/solr/activity/indexing.py
  OIPA/solr/indexing.py
  OIPA/solr/utils.py
Labels: size/L

#2400 Create greetings.yml
  .github/workflows/greetings.yml
Labels: size/S
