Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-09, with the labels that each got.

#2421 release
  .circleci/config.yml
  .releaserc.json
  OIPA/api/iati/references.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/tasks.py
  OIPA/solr/indexing.py
  OIPA/solr/result/serializers.py
  OIPA/solr/transaction/conf/xslt/transaction-csv.xsl
  OIPA/solr/transaction/tasks.py
  OIPA/solr/utils.py
  OIPA/task_queue/download.py
Labels: size/L

#2424 OIPA-2417
  OIPA/api/iati/references.py
  OIPA/solr/activity/references.py
Labels: size/XS

#2425 fix: document-link/category name fixed
  OIPA/api/iati/references.py
  OIPA/solr/activity/references.py
Labels: size/XS

#2412 OIPA-2394
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_activities_csv_endpoints.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/budget/views.py
  OIPA/api/transaction/views.py
  OIPA/iati/migrations/0071_auto_20200904_0706.py
  OIPA/iati/models.py
  OIPA/iati/parser/post_save_validators.py
  OIPA/iati/tests/test_parser_post_models.py
  OIPA/iati/transaction/models.py
  OIPA/solr/activity/indexing.py
Labels: size/L

#2432 OIPA-2431
  OIPA/api/budget/views.py
  OIPA/api/transaction/views.py
Labels: size/S

#2455 Two Factor Authenticatioon
  OIPA/OIPA/settings.py
  OIPA/OIPA/urls.py
  OIPA/templates/two_factor/_base.html
  OIPA/templates/two_factor/_base_focus.html
Labels: size/L

#2456 Revert "Two Factor Authenticatioon"
  OIPA/OIPA/settings.py
  OIPA/OIPA/urls.py
  OIPA/templates/two_factor/_base.html
  OIPA/templates/two_factor/_base_focus.html
Labels: size/L

#2454 Release
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_activities_csv_endpoints.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/budget/views.py
  OIPA/api/transaction/views.py
  OIPA/iati/migrations/0071_auto_20200904_0706.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/parser/post_save_validators.py
  OIPA/iati/tests/test_parser_post_models.py
  OIPA/iati/transaction/models.py
  OIPA/solr/activity/indexing.py
  OIPA/solr/signals.py
  OIPA/task_queue/validation.py
Labels: size/XL

#2458 Two Factor Authentication
  OIPA/OIPA/settings.py
  OIPA/OIPA/urls.py
  OIPA/requirements.txt
  OIPA/templates/two_factor/_base.html
  OIPA/templates/two_factor/_base_focus.html
Labels: size/L
