Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-05, with the labels that each got.

#2235 DEV-373
  .circleci/config.yml
Labels: size/M

#2227 OIPA-2220
  OIPA/api/generics/views.py
Labels: size/XS

#2217 OIPA-2216
  OIPA/OIPA/settings.py
  OIPA/api/region/tests/test_region_endpoints.py
  OIPA/geodata/migrations/0001_initial.py
  OIPA/geodata/migrations/0006_auto_20200424_1113.py
  OIPA/geodata/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_organisation/parser/organisation_2_03.py
  OIPA/iati_synchroniser/m49_regions_importer.py
  OIPA/plugins/data/regions.json
Labels: size/L

#2238 OIPA-2222
  OIPA/solr/budget/conf/xslt/budget-csv.xsl
Labels: size/S

#2162 #2160
  Dockerfile
Labels: size/S

#2245 OIPA-2226
  OIPA/OIPA/settings.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/requirements.txt
  OIPA/task_queue/tasks.py
Labels: size/S

#2244 OIPA-2215
  OIPA/iati/filegrabber.py
  OIPA/task_queue/validation.py
Labels: size/M

#2240 OIPA 2218
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/iati_synchroniser/data/vocab7.json
  OIPA/iati_synchroniser/vocab7_importer.py
Labels: size/L

#2239 Oipa-2225
  OIPA/api/iati/references.py
Labels: size/S

#2246 Release
  .circleci/config.yml
  Dockerfile
  OIPA/OIPA/settings.py
  OIPA/api/dataset/filters.py
  OIPA/api/dataset/serializers.py
  OIPA/api/generics/views.py
  OIPA/api/iati/references.py
  OIPA/api/region/tests/test_region_endpoints.py
  OIPA/geodata/migrations/0001_initial.py
  OIPA/geodata/migrations/0006_auto_20200424_1113.py
  OIPA/geodata/models.py
  OIPA/iati/PostmanJsonImport/importPostmanJson.py
  OIPA/iati/filegrabber.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_organisation/parser/organisation_2_03.py
  OIPA/iati_synchroniser/aid_type_codes_for_vocab3_importer.py
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/iati_synchroniser/data/aid_type_vocab3.json
  OIPA/iati_synchroniser/data/vocab7.json
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/m49_regions_importer.py
  OIPA/iati_synchroniser/migrations/0017_auto_20200317_1516.py
  OIPA/iati_synchroniser/migrations/0017_dataset_validation_status.py
  OIPA/iati_synchroniser/migrations/0018_dataset_validation_md5.py
  OIPA/iati_synchroniser/migrations/0019_rename_md5_to_sha1.py
  OIPA/iati_synchroniser/migrations/0020_sha1_to_sha512.py
  OIPA/iati_synchroniser/models.py
  OIPA/iati_synchroniser/vocab7_importer.py
  OIPA/plugins/data/regions.json
  OIPA/requirements.txt
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/conf/xslt/budget-csv.xsl
  OIPA/solr/budget/indexing.py
  OIPA/task_queue/tasks.py
  OIPA/task_queue/validation.py
  README.MD
Labels: size/XXL

#2253 OIPA-2250
  OIPA/api/activity/views.py
  OIPA/api/region/serializers.py
Labels: size/XS

#2254 update
  OIPA/api/activity/views.py
  OIPA/api/region/serializers.py
Labels: size/XS

#2237 Oipa-2151
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/solr/activity/indexing.py
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
Labels: size/L

#2255 Optimization
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/parser/iati_parser.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati/tests/test_parser_fields.py
  OIPA/iati_synchroniser/models.py
  OIPA/solr/signals.py
  OIPA/task_queue/tasks.py
Labels: size/L

#2270 OIPA-2226
  OIPA/task_queue/tasks.py
Labels: size/S
