Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-06, with the labels that each got.

#2279 DEV-383
  OIPA/task_queue/tasks.py
Labels: size/XS

#2272 OIPA-2248
  OIPA/solr/utils.py
Labels: size/XS

#2271 OIPA-2226
  OIPA/task_queue/tasks.py
Labels: size/S

#2281 OIPA-2219
  OIPA/solr/activity/indexing.py
  OIPA/solr/transaction/serializers.py
Labels: size/M

#2276 OIPA-2198
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
Labels: size/L

#2284 OIPA-2268
  OIPA/OIPA/settings.py
  OIPA/solr/activity/tasks.py
  OIPA/solr/activity_sector/conf/managed-schema
  OIPA/solr/activity_sector/indexing.py
  OIPA/solr/activity_sector/tasks.py
  OIPA/solr/signals.py
  OIPA/solr/transaction/tasks.py
  OIPA/solr/transaction_sector/indexing.py
  OIPA/solr/transaction_sector/tasks.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
Labels: size/XXL

#2294 OIPA-2275
  OIPA/solr/transaction/conf/xslt/transaction-csv.xsl
Labels: size/M

#2297 OIPA-2275
  OIPA/solr/transaction/conf/xslt/transaction-csv.xsl
Labels: size/XS

#2301 OIPA-2273
  OIPA/iati_synchroniser/admin.py
Labels: size/XS

#2311 OIPA-2299
  OIPA/iati/parser/post_save.py
  OIPA/solr/activity/indexing.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
Labels: size/XS

#2318 OIPA-2317
  OIPA/solr/activity/tasks.py
  OIPA/solr/activity_sector/tasks.py
  OIPA/solr/budget/tasks.py
  OIPA/solr/dataset/tasks.py
  OIPA/solr/organisation/tasks.py
  OIPA/solr/publisher/tasks.py
  OIPA/solr/result/tasks.py
  OIPA/solr/transaction/tasks.py
  OIPA/solr/transaction_sector/tasks.py
  OIPA/task_queue/tasks.py
Labels: size/S

#2316 OIPA-2303
  OIPA/solr/activity/indexing.py
Labels: size/XS

#2315 OIPA-2310
  OIPA/api/iati/references.py
Labels: size/XS

#2321 OIPA-2307
  OIPA/solr/activity/conf/xslt/activity-xml.xsl
Labels: size/S

#2328 OIPA-2313
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/solr/activity/indexing.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
Labels: size/S

#2329 OIPA-2308
  OIPA/solr/activity/conf/xslt/activity-xml.xsl
Labels: size/S
