Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-02, with the labels that each got.

#2087 Iati.cloud-2068
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/solr/organisation/conf/managed-schema
  OIPA/solr/organisation/conf/xslt/organisation-xml.xsl
  OIPA/solr/organisation/indexing.py
  OIPA/solr/organisation/references.py
Labels: size/L

#2092 iati.cloud-1844
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/solr/utils.py
Labels: size/L

#2098 OIPA-2093 + 2094 + 2085
  OIPA/api/generics/views.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/tests/test_parser_fields.py
  OIPA/iati_codelists/fixtures/test_codelists.json
  OIPA/iati_codelists/migrations/0001_initial.py
  OIPA/iati_codelists/models.py
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
Labels: size/M

#2112 Iati.cloud-2038
  OIPA/OIPA/settings.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0017_dataset_validation_status.py
  OIPA/iati_synchroniser/migrations/0018_dataset_validation_md5.py
  OIPA/iati_synchroniser/migrations/0019_rename_md5_to_sha1.py
  OIPA/iati_synchroniser/migrations/0020_sha1_to_sha512.py
  OIPA/iati_synchroniser/models.py
  OIPA/iati_synchroniser/tests/test_create_publisher_organisation.py
  OIPA/iati_synchroniser/tests/test_dataset_syncer.py
  OIPA/iati_synchroniser/tests/test_m49_regions_importer.py
  OIPA/task_queue/tasks.py
  OIPA/task_queue/utils.py
  OIPA/task_queue/validation.py
Labels: size/L

#2115 feat: ait_type codelist migration file added
  OIPA/iati_codelists/migrations/0015_auto_20200205_1401.py
Labels: size/S

#2117 OIPA-2116
  OIPA/OIPA/settings.py
  OIPA/task_queue/tasks.py
  OIPA/task_queue/validation.py
Labels: size/M

#2120 iati.cloud-2105
  OIPA/solr/transaction/conf/xslt/transaction-csv.xsl
Labels: size/L

#2121 OIPA-2119
  OIPA/api/iati/references.py
  OIPA/task_queue/tasks.py
Labels: size/M

#2123 OIPA-2102
  OIPA/api/result/views.py
  OIPA/iati/migrations/0069_auto_20200225_1416.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/parser/tests/test_2_03_parser.py
Labels: size/M
