Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-07, with the labels that each got.

#2339 Prerelease
  .circleci/config.yml
Labels: size/XS

#2343 latest_update_for_release
  OIPA/OIPA/settings.py
  OIPA/iati/migrations/0070_auto_20200703_1100.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/transaction/models.py
  OIPA/solr/activity/indexing.py
  OIPA/solr/activity/tasks.py
  OIPA/task_queue/tasks.py
  OIPA/task_queue/validation.py
Labels: size/L

#2346 OIPA-2345
  OIPA/iati_synchroniser/models.py
Labels: size/XS

#2350 OIPA-2323
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/transaction/indexing.py
Labels: size/S

#2357 OIPA-2352
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
Labels: size/XS

#2280 Oipa-1643
  OIPA/api/activity/filters.py
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_activities_csv_endpoints.py
  OIPA/api/activity/tests/test_prefetches.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/activity/views.py
  OIPA/api/iati/references.py
  OIPA/api/renderers.py
Labels: size/L

#2358 OIPA-1643
  OIPA/api/activity/filters.py
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_activities_csv_endpoints.py
  OIPA/api/activity/tests/test_prefetches.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/activity/views.py
  OIPA/api/iati/references.py
  OIPA/api/renderers.py
Labels: size/L

#2361 OIPA-2359
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/codelist/serializers.py
Labels: size/L

#2364 OIPA-2359
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/tests/test_organisation_csv_endpoint.py
Labels: size/M

#2365 OIPA-2327
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/task_queue/download.py
  OIPA/task_queue/tasks.py
Labels: size/L

#2369 Release
  OIPA/api/activity/serializers.py
  OIPA/api/activity/tests/test_serializers.py
  OIPA/api/codelist/serializers.py
  OIPA/api/organisation/serializers.py
  OIPA/api/organisation/tests/test_organisation_csv_endpoint.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/transaction/indexing.py
  OIPA/task_queue/download.py
  OIPA/task_queue/tasks.py
Labels: size/L

#2372 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: size/M
