Repository zimmerman-team/IATI.cloud, pull requests merged in 2020-04, with the labels that each got.

#2171 #2170
  .circleci/config.yml
  .releaserc.json
  OIPA/iati/parser/tests/test_2_03_parser.py
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/iati_synchroniser/humanitrian_global_clusters_import.py
Labels: size/L

#2176 Release to master
  .circleci/config.yml
  .releaserc.json
  Dockerfile
  OIPA/OIPA/settings.py
  OIPA/api/country/serializers.py
  OIPA/api/country/tests/test_country_serializers.py
  OIPA/api/generics/views.py
  OIPA/api/iati/elements.py
  OIPA/api/iati/references.py
  OIPA/api/renderers.py
  OIPA/api/result/views.py
  OIPA/iati/migrations/0069_auto_20200225_1416.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati/parser/tests/test_2_03_parser.py
  OIPA/iati/tests/test_parser_fields.py
  OIPA/iati_codelists/fixtures/test_codelists.json
  OIPA/iati_codelists/migrations/0001_initial.py
  OIPA/iati_codelists/migrations/0015_auto_20200205_1401.py
  OIPA/iati_codelists/migrations/0016_auto_20200310_1138.py
  OIPA/iati_codelists/models.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/iati_synchroniser/data/humanitarian_global_clusters.json
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/humanitrian_global_clusters_import.py
  OIPA/iati_synchroniser/migrations/0017_dataset_validation_status.py
  OIPA/iati_synchroniser/migrations/0018_dataset_validation_md5.py
  OIPA/iati_synchroniser/migrations/0019_rename_md5_to_sha1.py
  OIPA/iati_synchroniser/migrations/0020_sha1_to_sha512.py
  OIPA/iati_synchroniser/models.py
  OIPA/iati_synchroniser/tests/test_create_publisher_organisation.py
  OIPA/iati_synchroniser/tests/test_dataset_syncer.py
  OIPA/iati_synchroniser/tests/test_m49_regions_importer.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/solr/activity/indexing.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
  OIPA/solr/organisation/conf/managed-schema
  OIPA/solr/organisation/conf/xslt/organisation-xml.xsl
  OIPA/solr/organisation/indexing.py
  OIPA/solr/organisation/references.py
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/conf/xslt/transaction-csv.xsl
  OIPA/solr/transaction/indexing.py
  OIPA/solr/utils.py
  OIPA/static/xml/activity-standard-example-annotated-203.xml
  OIPA/task_queue/tasks.py
  OIPA/task_queue/utils.py
  OIPA/task_queue/validation.py
  README.MD
Labels: size/XXL

#2159 OIPA-2157
  OIPA/OIPA/settings.py
  OIPA/api/dataset/filters.py
  OIPA/api/generics/views.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0017_auto_20200317_1516.py
  OIPA/iati_synchroniser/migrations/0017_dataset_validation_status.py
  OIPA/iati_synchroniser/migrations/0018_dataset_validation_md5.py
  OIPA/iati_synchroniser/migrations/0019_rename_md5_to_sha1.py
  OIPA/iati_synchroniser/migrations/0020_sha1_to_sha512.py
  OIPA/iati_synchroniser/models.py
  OIPA/requirements.txt
  OIPA/task_queue/tasks.py
  OIPA/task_queue/validation.py
Labels: size/L

#2184 OIPA-2172-1
  OIPA/OIPA/settings.py
  OIPA/api/dataset/serializers.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/task_queue/tasks.py
  OIPA/task_queue/validation.py
Labels: size/S

#2189 OIPA-2186
  OIPA/iati/PostmanJsonImport/importPostmanJson.py
Labels: size/XS

#2197 OIPA-2191
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
  OIPA/task_queue/tasks.py
Labels: size/M

#2200 OIPA-2191
  OIPA/task_queue/tasks.py
Labels: size/M

#2201 OIPA-2191
  OIPA/OIPA/settings.py
Labels: size/XS

#2203 OIPA-2191
  OIPA/OIPA/settings.py
Labels: size/XS

#2204 OIPA-2191
  OIPA/OIPA/settings.py
Labels: size/XS

#2206 OIPA-2104
  OIPA/solr/budget/conf/xslt/budget-csv.xsl
Labels: size/M

#2209 OIPA-2185
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
Labels: size/XS

#2202 Oipa 2173
  OIPA/api/dataset/serializers.py
Labels: size/XS

#2188 Minor copy changes
  README.MD
Labels: size/XS

#2212 OIPA-2210
  OIPA/iati_synchroniser/aid_type_codes_for_vocab3_importer.py
  OIPA/iati_synchroniser/codelist_importer.py
  OIPA/iati_synchroniser/data/aid_type_vocab3.json
Labels: size/L

#2187 OIPA-2100
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
Labels: size/L

#2228 OIPA-2224
  OIPA/solr/activity/conf/xslt/activity-csv.xsl
Labels: size/XS
