Repository zimmerman-team/IATI.cloud, pull requests merged in 2021-02, with the labels that each got.

#2539 activity/transaction/budget data and filters
  OIPA/api/activity/filters.py
  OIPA/iati/migrations/0077_auto_20210111_1628.py
  OIPA/iati/models.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
  OIPA/solr/indexing.py
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
Labels: size/XL

#2540 release
  OIPA/api/activity/filters.py
  OIPA/api/dataset/filters.py
  OIPA/api/dataset/serializers.py
  OIPA/api/dataset/urls.py
  OIPA/api/dataset/views.py
  OIPA/iati/migrations/0077_auto_20210111_1628.py
  OIPA/iati/models.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0021_datasetfailedpickup.py
  OIPA/iati_synchroniser/models.py
  OIPA/requirements.txt
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/budget/conf/managed-schema
  OIPA/solr/budget/indexing.py
  OIPA/solr/indexing.py
  OIPA/solr/signals.py
  OIPA/solr/transaction/conf/managed-schema
  OIPA/solr/transaction/indexing.py
  OIPA/task_queue/download.py
  OIPA/task_queue/tasks.py
Labels: size/XL

#2545 Add commitlint to iati.cloud (gb-66)
  .pre-commit-config.yaml
  OIPA/requirements.txt
  README.MD
  commitlint.config.js
Labels: size/S

#2550 OIPA-2543
  OIPA/api/activity/filters.py
  OIPA/task_queue/validation.py
Labels: size/L
