Repository zimmerman-team/IATI.cloud, pull requests merged in 2021-01, with the labels that each got.

#2485 Fix broken circle-ci badge
  README.MD
Labels: size/XS

#2509 Fixed both API bugs
  OIPA/api/transaction/filters.py
Labels: size/XS

#2532 Fix flake8 errors
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/solr/signals.py
  OIPA/task_queue/download.py
  OIPA/task_queue/tasks.py
Labels: size/S

#2521 Sum of multi-value USD fields
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/solr/activity/conf/managed-schema
  OIPA/solr/activity/indexing.py
  OIPA/solr/indexing.py
  OIPA/solr/signals.py
  OIPA/task_queue/download.py
  OIPA/task_queue/tasks.py
Labels: size/M

#2524 Update activity tag field length (Oipa 2520)
  OIPA/iati/migrations/0077_auto_20210111_1628.py
  OIPA/iati/models.py
Labels: size/S
