Repository zimmerman-team/IATI.cloud, pull requests merged in 2021-03, with the labels that each got.

#2568 Fix CI workflow
  .circleci/config.yml
  OIPA/requirements.txt
Labels: size/XS

#2558 docs: updated README.MD to reflect the most recent production release
  README.MD
Labels: size/L

#2566 fix: update AidType model to allow 4 characters
  OIPA/iati_codelists/migrations/0017_auto_20210302_1418.py
  OIPA/iati_codelists/models.py
Labels: size/S

#2557 Disable and re-organise unused tasks
  OIPA/OIPA/celery.py
  OIPA/task_queue/tasks.py
Labels: size/XL

#2554 Feature/update django admin
  OIPA/OIPA/urls.py
  OIPA/geodata/admin.py
  OIPA/iati_synchroniser/admin.py
Labels: size/M

#2575 docs: fix psql link
  README.MD
Labels: size/XS

#2574 fix: readme to contain proper links to sonarcloud and issues
  README.MD
Labels: size/XS

#2577 Allow IATI parser to process comma separated numberic values
  OIPA/iati/parser/iati_parser.py
  OIPA/iati_organisation/migrations/0009_auto_20210312_1410.py
  OIPA/iati_organisation/models.py
Labels: size/S

#2581 Sha1 per activity redeploy
  OIPA/iati/migrations/0078_activity_sha1.py
  OIPA/iati/models.py
  OIPA/iati/parser/IATI_2_02.py
  OIPA/iati/parser/IATI_2_03.py
  OIPA/iati/parser/iati_parser.py
  OIPA/iati/tests/test_parser_post_save_file.py
  OIPA/iati_organisation/parser/organisation_2_01.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_organisation/parser/organisation_2_03.py
Labels: size/M

#2567 Drop old datasets
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0022_datasetupdatedates.py
  OIPA/iati_synchroniser/models.py
  OIPA/task_queue/download.py
  OIPA/task_queue/tasks.py
Labels: size/L

#2576 Change api list with datasets that could not be picked up to a more logical implementation
  OIPA/api/dataset/filters.py
  OIPA/api/dataset/serializers.py
  OIPA/api/dataset/views.py
  OIPA/api/organisation/serializers.py
  OIPA/iati/parser/parse_manager.py
  OIPA/iati_organisation/migrations/0009_auto_20210312_1410.py
  OIPA/iati_organisation/models.py
  OIPA/iati_organisation/parser/organisation_2_02.py
  OIPA/iati_synchroniser/dataset_syncer.py
  OIPA/iati_synchroniser/migrations/0023_auto_20210311_1111.py
  OIPA/iati_synchroniser/models.py
  OIPA/task_queue/download.py
Labels: size/L

#2588 Include result type in Solr output
  OIPA/solr/result/conf/managed-schema
  OIPA/solr/result/indexing.py
Labels: size/XS
